export const copy = {
  ar: {
    brand: 'أطلس', journey: 'رحلتك', exploreGlobe: 'استكشف الكرة الأرضية', countries: 'الدول', progress: 'تقدّمك', countriesLearned: 'دول حفظتها', exploredPercent: 'من العالم اكتشفته', quickView: 'عرض سريع', allCountries: 'كل الدول', memorized: 'تم حفظها', toDiscover: 'بانتظار اكتشافها', footer: 'صُنع للعقول الفضولية', explore: 'استكشف', worldMap: 'خريطة العالم', pace: 'عالمك، على وتيرتك', switchTheme: 'تغيير المظهر', switchLanguage: 'التبديل إلى الإنجليزية', eyebrow: 'طريقة تفاعلية للتعلّم', heroLine1: 'العالم بين يديك', heroLine2: 'لتكتشفه.', heroBody: 'أدر الكرة الأرضية، وتعرّف على الدول، واجعل كل مكان مألوفًا أكثر.', interactiveGlobe: 'الكرة الأرضية التفاعلية', exploreWorld: 'استكشف العالم', surprise: 'فاجئني', dragExplore: 'اسحب للاستكشاف', zoomIn: 'تكبير', zoomOut: 'تصغير', rotateGlobe: 'تدوير الكرة الأرضية', stopRotation: 'إيقاف التدوير', toExplore: 'لم تُحفظ', selected: 'المحددة', dragHint: 'اسحب للتدوير · مرّر للتكبير', findPlace: 'ابحث عن مكان', searchPlaceholder: 'ابحث بالعربية أو الإنجليزية...', noResults: 'لم يتم العثور على دول.', spotlight: 'دولة تحت المجهر', ready: 'جاهزة للاكتشاف', capitalCity: 'العاصمة', region: 'القارة', markMemorized: 'حفظت هذه الدولة', removeMemorized: 'تم حفظها', learnedNote: 'عمل رائع! يمكنك تغيير هذا في أي وقت.', learnNote: 'هل حفظتها؟ أضفها إلى مجموعتك.', mapLabel: 'كرة أرضية تفاعلية تعرض الدول', learned: 'محفوظة', login: 'دخول', account: 'حسابي', logout: 'تسجيل الخروج', logoutError: 'تعذر تسجيل الخروج. حاول مرة أخرى.', loadingProgress: 'جارٍ تحميل تقدّمك…', syncError: 'تعذر مزامنة التقدّم.', retry: 'أعد المحاولة', dailyStreak: 'السلسلة اليومية', streakDay: 'يوم', streakDays: 'أيام', streakDone: 'أنجزت هدف اليوم', streakStarted: 'بدأت سلسلتك اليوم!', streakGoal: 'احفظ دولة اليوم', streakPopupStart: 'بدأت سلسلتك!', streakPopupContinue: 'واصلت سلسلتك!', streakPopupStartBody: 'عُد غدًا لتحافظ عليها.', streakPopupContinueBody: 'رائع! تعلمت دولة اليوم.', streakDismiss: 'إغلاق'
  },
  en: {
    brand: 'atlas', journey: 'YOUR JOURNEY', exploreGlobe: 'Explore globe', countries: 'Countries', progress: 'YOUR PROGRESS', countriesLearned: 'Countries learned', exploredPercent: 'of the world explored', quickView: 'QUICK VIEW', allCountries: 'All countries', memorized: 'Memorized', toDiscover: 'To discover', footer: 'Made for curious minds', explore: 'EXPLORE', worldMap: 'WORLD MAP', pace: 'YOUR WORLD, YOUR PACE', switchTheme: 'Toggle dark mode', switchLanguage: 'Switch to Arabic', eyebrow: 'AN INTERACTIVE WAY TO LEARN', heroLine1: 'The world is yours', heroLine2: 'to discover.', heroBody: 'Spin the globe, explore a country, and make every place a little more familiar.', interactiveGlobe: 'THE INTERACTIVE GLOBE', exploreWorld: 'Explore the world', surprise: 'Surprise me', dragExplore: 'DRAG TO EXPLORE', zoomIn: 'Zoom in', zoomOut: 'Zoom out', rotateGlobe: 'Rotate globe', stopRotation: 'Stop rotation', toExplore: 'To explore', selected: 'Selected', dragHint: 'Drag to rotate · Scroll to zoom', findPlace: 'FIND A PLACE', searchPlaceholder: 'Search in English or Arabic...', noResults: 'No countries found.', spotlight: 'COUNTRY SPOTLIGHT', ready: 'READY TO DISCOVER', capitalCity: 'CAPITAL CITY', region: 'REGION', markMemorized: 'Mark as memorized', removeMemorized: 'Memorized', learnedNote: 'Great work! You can always change this.', learnNote: 'Learned it? Add it to your collection.', mapLabel: 'Interactive globe showing countries', learned: 'MEMORIZED', login: 'Log in', account: 'My account', logout: 'Log out', logoutError: 'Could not log out. Please try again.', loadingProgress: 'Loading your progress…', syncError: 'Could not sync progress.', retry: 'Retry', dailyStreak: 'Daily streak', streakDay: 'day', streakDays: 'days', streakDone: "Today's goal complete", streakStarted: 'Your streak starts today!', streakGoal: 'Memorize a country today', streakPopupStart: 'Your streak has begun!', streakPopupContinue: 'Your streak keeps growing!', streakPopupStartBody: 'Come back tomorrow to keep it going.', streakPopupContinueBody: 'You learned a country today. Nice work!', streakDismiss: 'Dismiss'
  }
};

const arabicNames = new Intl.DisplayNames(['ar'], { type: 'region' });
const arabicCapitals = {
  AF:'كابل', AL:'تيرانا', DZ:'الجزائر', AD:'أندورا لا فيلا', AO:'لواندا', AG:'سانت جونز', AR:'بوينس آيرس', AM:'يريفان', AU:'كانبرا', AT:'فيينا', AZ:'باكو', BS:'ناساو', BH:'المنامة', BD:'دكا', BB:'بريدجتاون', BY:'مينسك', BE:'بروكسل', BZ:'بلموبان', BJ:'بورتو نوفو', BT:'تيمفو', BO:'سوكري', BA:'سراييفو', BW:'غابورون', BR:'برازيليا', BN:'بندر سري بكاوان', BG:'صوفيا', BF:'واغادوغو', BI:'غيتيغا', CV:'برايا', KH:'بنوم بنه', CM:'ياوندي', CA:'أوتاوا', CF:'بانغي', TD:'إنجامينا', CL:'سانتياغو', CN:'بكين', CO:'بوغوتا', KM:'موروني', CG:'برازافيل', CD:'كينشاسا', CR:'سان خوسيه', CI:'ياموسوكرو', HR:'زغرب', CU:'هافانا', CY:'نيقوسيا', CZ:'براغ', DK:'كوبنهاغن', DJ:'جيبوتي', DM:'روسو', DO:'سانتو دومينغو', EC:'كيتو', EG:'القاهرة', SV:'سان سلفادور', GQ:'مالابو', ER:'أسمرة', EE:'تالين', SZ:'لوبامبا', ET:'أديس أبابا', FJ:'سوفا', FI:'هلسنكي', FR:'باريس', GA:'ليبرفيل', GM:'بانجول', GE:'تبليسي', DE:'برلين', GH:'أكرا', GR:'أثينا', GD:'سانت جورجز', GT:'مدينة غواتيمالا', GN:'كوناكري', GW:'بيساو', GY:'جورج تاون', HT:'بورت أو برنس', HN:'تيغوسيغالبا', HU:'بودابست', IS:'ريكيافيك', IN:'نيودلهي', ID:'جاكرتا', IR:'طهران', IQ:'بغداد', IE:'دبلن', IL:'القدس', IT:'روما', JM:'كينغستون', JP:'طوكيو', JO:'عمّان', KZ:'أستانا', KE:'نيروبي', KI:'جنوب تاراوا', KP:'بيونغ يانغ', KR:'سيول', KW:'مدينة الكويت', KG:'بشكيك', LA:'فيينتيان', LV:'ريغا', LB:'بيروت', LS:'ماسيرو', LR:'مونروفيا', LY:'طرابلس', LI:'فادوز', LT:'فيلنيوس', LU:'لوكسمبورغ', MG:'أنتاناناريفو', MW:'ليلونغوي', MY:'كوالالمبور', MV:'ماليه', ML:'باماكو', MT:'فاليتا', MH:'ماجورو', MR:'نواكشوط', MU:'بورت لويس', MX:'مكسيكو سيتي', FM:'باليكير', MD:'كيشيناو', MC:'موناكو', MN:'أولان باتور', ME:'بودغوريتسا', MA:'الرباط', MZ:'مابوتو', MM:'نايبيداو', NA:'ويندهوك', NR:'يارين', NP:'كاتماندو', NL:'أمستردام', NZ:'ويلينغتون', NI:'ماناغوا', NE:'نيامي', NG:'أبوجا', MK:'سكوبيه', NO:'أوسلو', OM:'مسقط', PK:'إسلام آباد', PW:'نغيرولمود', PS:'رام الله', PA:'مدينة بنما', PG:'بورت مورسبي', PY:'أسونسيون', PE:'ليما', PH:'مانيلا', PL:'وارسو', PT:'لشبونة', QA:'الدوحة', RO:'بوخارست', RU:'موسكو', RW:'كيغالي', KN:'باستير', LC:'كاستريس', VC:'كينغستاون', WS:'آبيا', SM:'سان مارينو', ST:'ساو تومي', SA:'الرياض', SN:'داكار', RS:'بلغراد', SC:'فيكتوريا', SL:'فريتاون', SG:'سنغافورة', SK:'براتيسلافا', SI:'ليوبليانا', SB:'هونيارا', SO:'مقديشو', ZA:'بريتوريا', SS:'جوبا', ES:'مدريد', LK:'سري جاياواردنابورا كوتي', SD:'الخرطوم', SR:'باراماريبو', SE:'ستوكهولم', CH:'برن', SY:'دمشق', TJ:'دوشنبه', TZ:'دودوما', TH:'بانكوك', TL:'ديلي', TG:'لومي', TO:'نوكوالوفا', TT:'بورت أوف سبين', TN:'تونس', TR:'أنقرة', TM:'عشق آباد', TV:'فونافوتي', UG:'كمبالا', UA:'كييف', AE:'أبوظبي', GB:'لندن', US:'واشنطن العاصمة', UY:'مونتيفيديو', UZ:'طشقند', VU:'بورت فيلا', VA:'مدينة الفاتيكان', VE:'كاراكاس', VN:'هانوي', YE:'صنعاء', ZM:'لوساكا', ZW:'هراري'
};
const nameOverrides = {CN:'الصين', PS:'فلسطين', VA:'الفاتيكان', CI:'ساحل العاج', CD:'جمهورية الكونغو الديمقراطية', CG:'جمهورية الكونغو', CZ:'التشيك', KR:'كوريا الجنوبية', KP:'كوريا الشمالية', SZ:'إسواتيني', TL:'تيمور الشرقية'};
const continents = { Africa:'أفريقيا', Americas:'الأمريكتان', Asia:'آسيا', Europe:'أوروبا', Oceania:'أوقيانوسيا', Antarctica:'القارة القطبية الجنوبية' };
export function countryName(country, language) { return language === 'ar' ? (nameOverrides[country.id] || arabicNames.of(country.id) || country.name) : country.name; }
export function capitalName(country, language) { return language === 'ar' ? (arabicCapitals[country.id] || country.capital) : country.capital; }
export function continentName(country, language) { return language === 'ar' ? (continents[country.continent] || country.continent) : country.continent; }
